src/Entity/Question.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: \App\Repository\QuestionRepository::class)]
class Question
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Hall::class, inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private $hall;

    #[ORM\Column(type: 'string', length: 255)]
    private $question;

    #[ORM\Column(type: 'text')]
    private $answers;

    #[ORM\OneToMany(targetEntity: Answer::class, mappedBy: 'question', orphanRemoval: true)]
    private $toto; // Useless, just for the orphanRemoval.

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $text;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHall(): ?Hall
    {
        return $this->hall;
    }

    public function setHall(?Hall $hall): self
    {
        $this->hall = $hall;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAnswers(): ?string
    {
        return $this->answers;
    }

    public function getGoodAnswer(): ?string
    {
        return $this->getAnswer(0);
    }

    public function isGoodAnswer(string $answer): bool
    {
        return $answer == $this->getGoodAnswer();
    }

    public function getAnswer(int $pos): ?string
    {
        $answers = explode("\n", (string) $this->answers);
        return $answers[$pos] ?? null;
    }

    public function getAnswersCount(): int
    {
        $answers = explode("\n", (string) $this->answers);
        return count($answers);
    }

    /**
     * (for Admin)
     * @return string
     */
    public function getAnswersHtml(): string
    {
        $str  = "<span style='color:green;'>";
        $str .= str_replace("\n", "</span>; <span>", strip_tags((string) $this->answers));
        $str .= "</span>";

        return $str;
    }

    /**
     * (for players)
     * @return array
     */
    public function getAnswersRandom(): array
    {
        $answers = explode("\n", (string) $this->answers);
        shuffle($answers);
        return $answers;
    }

    public function setAnswers(string $answers): self
    {
        $this->answers = str_replace("\r", '', $answers);

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function __toString()
    {
        return $this->question;
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Entity\Hall;
use App\Entity\Player;
use App\Entity\Pub;
use App\Entity\Question;
use App\Service\MailService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route(path: '/jeu')]
#[IsGranted('ROLE_USER')]
class GameController extends AbstractController
{
    #[Route(path: '/fin', name: 'game_end')]
    public function end()
    {
        return $this->render('game/end.html.twig');
    }

    #[Route(path: '/halls', name: 'game_halls')]
    public function halls(EntityManagerInterface $em)
    {
        /** @var Player $player */
        $player = $this->getUser();

        if ($player->isAnonyme()) {
            return $this->redirectToRoute("game_player_infos");
        }

        $halls = $em->getRepository(Hall::class)->findBy([], ['tri' => 'ASC']);

        return $this->render('game/halls.html.twig', [
            'halls' => $halls,
            'player' => $player
        ]);
    }

    #[Route(path: '/halls/{name}', name: 'game_hall')]
    public function hall(Request $request, EntityManagerInterface $em, Hall $hall)
    {
        /** @var Player $user */
        $user = $this->getUser();

        /** @var Question $question */
        $question = $hall->getQuestion();

        $halls = $em->getRepository(Hall::class)->findBy([], ['name' => 'ASC']);

        $exclu = $hall->getExclu();
        $pubs = $hall->getPubs()->toArray();
        foreach ($pubs as $k => $pub) {
            if ($pub->isExclu()) unset($pubs[$k]);
        }
        shuffle($pubs);

        $partenaires = [];
        if ($exclu || isset($pubs[0])) $partenaires[] = $exclu ?? $pubs[0];
        if (isset($pubs[1])) $partenaires[] = $pubs[1];

        if ($request->isMethod("POST")) {

            $answer = $em->getRepository(Answer::class)->findOneBy([
                'player' => $user,
                'question' => $question
            ]);

            // Nouvelle réponse si pas existante
            if (null == $answer) {
                $answer = new Answer($user, $question);
            }

            // MAJ réponse
            $answer->setAnswer($request->request->get('answer'));
            $em->persist($answer);
            $user->addAnswer($answer);
            $user->updateLastConnection();
            $em->flush();


            // Liste des halls restants
            $hallTodo = [];
            foreach ($halls as $h) {
                if (!$user->isHallDone($h->getId())) {
                    $hallTodo[] = $h;
                }
            }

            return $this->render('game/answer.html.twig', [
                'halls' => $halls,
                'hallTodo' => $hallTodo,
                'player' => $user,
                'question' => $question,
                'hall' => $hall,
                'pubs' => $partenaires,
                'answer' => $answer
            ]);
        }

        return $this->render('game/question.html.twig', [
            'hall' => $hall,
            'player' => $user,
            'pubs' => $partenaires,
            'question' => $question
        ]);
    }


//    #[Route(path: '/code', name: 'game_token_signup')]
//    public function tokenLogin(EntityManagerInterface $em, Request $request)
//    {
//        $user = $this->getUser();
//        if (null !== $user && in_array("ROLE_USER", $user->getRoles())) {
//            return $this->redirectToRoute("game_halls");
//        }
//
//        $token = $request->query->get('t', null);
//
//        if ($token) {
//            $player = $em->getRepository(Player::class)->findOneByToken($token);
//            if ($player) {
//                // Manually authenticate user
//                $token = new UsernamePasswordToken($player, null, 'main', ["ROLE_USER"]);
//                $this->get('security.token_storage')->setToken($token);
//                $this->get('session')->set('_security_main', serialize($token));
//
//                return $this->redirectToRoute("game_halls");
//            }
//        }
//
//        return $this->render('game/code.html.twig');
//    }

//    #[Route(path: '/inscription-accueil', name: 'game_remote_signup')]
//    public function remoteSignup(Request $request) {
//        if ($request->isMethod("POST")) {
//
//            $player = $this->signupPlayer($request);
//
//            if ($player) {
//                return $this->render('game/qrcode.html.twig', [
//                    'player' => $player,
//                    'token' => $player->getToken()
//                ]);
//            }
//        }
//        return $this->render('game/signup.html.twig', [
//            'remote' => true,
//            'errors' => $this->errors,
//            'form' => $request->request->all()
//        ]);
//    }

//    private function signupPlayer(Request $request): ?Player
//    {
//        $post = $request->request->all();
//        //$email = $request->request->get('email');
//        //$name = $request->request->get('name', []);
//        //$name = trim(implode(' ', $name));
//        //$data = $request->request->get('data', []);
//        $email = $post['email'] ?? '';
//        $name = $post['name'] ?? [];
//        $name = trim(implode(' ', $name));
//        $data = $post['data'] ?? [];
//
//        $player = null;
//        $this->errors = [];
//
//        // Email unique (obligatoire, c'est le login)
//        $p = $this->em->getRepository(Player::class)->findOneByEmail($email);
//        if (empty($email) || null != $p) {
//            $this->errors['email'] = true;
//        }
//
//        // Tel unique
//        if (isset($data['tel'])) {
//            $p = $this->em->getRepository(Player::class)->findLikeDataTel($data['tel'] ?? '');
//            if (count($p) > 0) {
//                $this->errors['tel'] = true;
//            }
//        }
//
//        if (count($this->errors) > 0) {
//            return null;
//        }
//
//        $player = new Player();
//        $player->setName($name);
//        $player->setEmail($email);
//        $player->setData($data);
//
//        $token = substr(strtoupper(uniqid()), -6);
//        $player->setToken($token);
//
//        $this->em->persist($player);
//        $this->em->flush();
//
//        // Send email login url
//        $url = $this->router->generate('game_token_signup', [], UrlGeneratorInterface::ABSOLUTE_URL);
//        $url .= "?t=" . $token;
//
//        $message = <<<EOF
//Bienvenue au grand jeu Vikings de la foire de Rouen
//
//Cliquez ici pour vous connecter à votre compte et commencer à jouer :
//$url
//
//Bonne soirée !
//EOF;
//        $this->mail->send($player->getEmail(), $message);
//
//        return $player;
//    }

}

templates/game/answer.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper">
        
        <div class="clouds"></div>
        
        <div class="content">

            {% if app_gpdc %}

                <section>

                    <h1>Super !</h1>

                    <p>Votre note pour la prestation de {{ hall.name }} a bien été enregistrée.</p>

                    {% if hallTodo|length > 0 %}
                        <p>
                            Vous pouvez maintenant retourner à la liste des candidats pour attribuer d'autres notes.
                        </p>

                        <p>&nbsp;</p>

                        <p><a href="{{ path('game_halls') }}" class="button redButton">Retour à la liste des candidats</a></p>
                    {% else %}
                        <p>Vous avez noté tous nos candidats !</p>

                        <p><a href="{{ path('game_end') }}" class="button redButton">C'est fini !</a></p>
                    {% endif %}

                </section>

            {% else %}

                <section>

                        {% if answer.good %}
                            <h1>Bravo !</h1>
                        {% else %}
                            <h1>Dommage...</h1>
                        {% endif %}

                    <p>La bonne réponse était<br><strong>{{ question.goodAnswer }}</strong></p>

                    {% if hallTodo|length > 0 %}
                        <p>Il vous reste des énigmes à résoudre dans le{{ hallTodo|length > 1 ? 's' }}
                        {{ hallTodo|join(', ') }}</p>

                        <p><a href="{{ path('game_halls') }}" class="button redButton">Retour à la liste des halls</a></p>
                    {% else %}
                        <p>Vous avez répondu à l'ensemble des questions !</p>

                        <p><a href="{{ path('game_end') }}" class="button redButton">Fin du jeu</a></p>
                    {% endif %}

                </section>

            {% endif %}

            {% if pubs|length > 0 %}
            <section class="graySection">

                <h2>Nos partenaires du hall {{ hall.name }} :</h2>

                {% for pub in pubs %}
                    <p>
                        {% if pub.link is not null %}<a href="{{ pub.link }}" target="_blank">{% endif %}
                            <img src="/imgpub/{{ pub.image }}" width="300px">
                            {% if pub.link is not null %}</a>{% endif %}
                    </p>
                {% endfor %}

            </section>
            {% endif %}
        </div>
</div>




{% endblock content %}

templates/game/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, maximum-scale=5">

    <meta name="description" content='Grand Prix de la Chanson de Lillebonne'>

    <meta property="og:title" content='Grand Prix de la Chanson de Lillebonne'>
    <meta property="og:description" content='Votez pour votre candidat préféré'>
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ url('game_index') }}">
    <meta property="og:image" content="{{ url('game_index') }}img/title.png">

    <title>{% block title %}Grand Prix de la Chanson de Lillebonne{% endblock %}</title>
    
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">

</head>
<body>
    
    {# <a href="https://www.horizon-fm.fr/" target="_blank" id="horizonBanner" class="pas" title="Écouter en direct sur Horizon FM">
        À suivre sur <img src="{{ asset('img/logoHorizon.jpg') }}" alt="Horizon - La radio libre">
    </a> #}

    <header>
        {% if app.user %}
        id joueur : #{{ app.user.id }}
        {% endif %}
    </header>

    <style>
        #flashContainer {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000;
        }
        .flashMessage {
            display: block;
            width: 100%;
            padding: 1rem;
            font-size: 1.2rem;
            font-weight: bold;
            text-align: center;
            background-color: white;
            cursor: pointer;
        }
        .flashMessage.bg-navy {
            color: #001f3f;
        }
        .flashMessage.bg-aqua {
            color: #7FDBFF;
        }
        .flashMessage.bg-or {
            color: #FF851B;
        }
        .flashMessage.bg-red {
            color: #FF4136;
        }
    </style>
    <script>
        // close flash message
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('.flashMessage').forEach(function(el) {
                el.addEventListener('click', function() {
                    el.remove();
                });
            });
        }, false);
    </script>
    <div id="flashContainer">
        {# read and display all flash messages #}
        {# label : 'notice', 'success', 'warning', 'error' #}
        {% set class = {'notice':'bg-navy','success':'bg-aqua','warning':'bg-or','error':'bg-red'} %}
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flashMessage {{ class[label] }}">
                    {{ message|raw }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
    
    {% if app_gpdc %}
    
    <nav>
        <a href="#" aria-label="Afficher le menu" class="navLink"><img src="{{ asset('img/navIcon.svg') }}" alt="menu"></a>
        <ul>
            <li><a href="{{ path('game_index') }}">Voter pour le prix du public</a></li>
            <li><a href="{{ path('game_howto') }}">Comment participer ?</a></li>
            <li><a href="{{ path('game_rules') }}">Règlement</a></li>
        </ul>
    </nav>
    
    {% else %}
    
    <nav>
        <a href="#" aria-label="Afficher le menu" class="navLink"><img src="{{ asset('img/navIcon.svg') }}" alt="menu"></a>
        <ul>
            <li><a href="{{ path('game_index') }}">Le jeu</a></li>
            <li><a href="{{ path('game_howto') }}">Comment jouer ?</a></li>
            <li><a href="{{ asset('plan-foire.jpg') }}" target="_blank">Plan de la foire</a></li>
            <li><a href="{{ asset('reglement2022.pdf') }}" target="_blank">Règlement</a></li>
            {#<li><a href="{{ path('game_rules') }}">Règlement</a></li>#}
        </ul>
    </nav>
    
    {% endif %}

    

    

    {% block content %}{% endblock %}
    
    <script type="text/javascript" src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/main.js') }}"></script>

</body>
</html>

templates/game/closed.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper" class="bigCover">
        
        <div class="clouds"></div>
        
        <div class="content">

            <section>
                
                <div class="logo"><img src="/img/title.png" alt="Grand Prix de la Chanson"></div>

                <p><strong>À partir du 25 septembre</strong>, inscrivez-vous sur ce site pour pouvoir <strong>voter en live</strong> le samedi 28 septembre pour votre candidat préféré !</p>
                <p>Le grand gagnant recevra le Prix du public !</strong></p>

            </section>
            
            <section class="graySection">
                
                <p><img src="/img/lillebonne.png" alt="Ville de Lillebonne"></p>
                
            </section>
            
        </div>

</div>

{% endblock content %}

templates/game/code.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper">
        
    <div class="clouds"></div>

    <div class="content">

        <section>

            <h1>Inscription</h1>
            <h2>Vous avez un code ?</h2>
            
            <p>Pour vous connecter, renseignez le code unique indiqué sur le bulletin de participation qui vous à été remis à l'entrée.</p>

            <form method="get" action="{{ path('app_login_code') }}">
                <div class="codeForm">
                    <label>Mon code</label>
                    
                    <div></div>
                        
                    <input type="text" name="t" id="inputCode" required>

                    <style>
                        #scanButton:disabled {
                        }
                    </style>
                    <div>
                        <button type="button" id="scanButton" class="button redButton borderedButton">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#fff" style="width:20px;height: 20px;">
                              <path d="M12 9a3.75 3.75 0 100 7.5A3.75 3.75 0 0012 9z" />
                              <path fill-rule="evenodd" d="M9.344 3.071a49.52 49.52 0 015.312 0c.967.052 1.83.585 2.332 1.39l.821 1.317c.24.383.645.643 1.11.71.386.054.77.113 1.152.177 1.432.239 2.429 1.493 2.429 2.909V18a3 3 0 01-3 3h-15a3 3 0 01-3-3V9.574c0-1.416.997-2.67 2.429-2.909.382-.064.766-.123 1.151-.178a1.56 1.56 0 001.11-.71l.822-1.315a2.942 2.942 0 012.332-1.39zM6.75 12.75a5.25 5.25 0 1110.5 0 5.25 5.25 0 01-10.5 0zm12-1.5a.75.75 0 100-1.5.75.75 0 000 1.5z" clip-rule="evenodd" />
                            </svg>
                        </button>
                    </div>
                    {# ":disabled" si le navigateur ne supporte pas mediaDevices & BarcodeDetector #}

                </div>
                <p class="mtm"><button class="button redButton blockButton">Valider</button></p>
            </form>

            {% if app_inscription %}
            <p><a href="{{ path('app_register') }}">Je n'ai pas de code</a></p>
            {% endif %}

        </section>
    </div>
</div>

{# Code Scanner #}
<dialog id="videoDialig">
    <video id="video" width="640" height="480" autoplay></video>
</dialog>

<script>
    // https://www.jsnow.io/p/javascript/creating-a-real-time-qr-code-scanner-with-vanilla-javascript-part-1
    // https://www.jsnow.io/p/javascript/creating-a-real-time-qr-code-scanner-with-javascript-part-2

    const video = document.querySelector('#video')
    const videoDialog = document.querySelector('#videoDialig')
    const scanButton = document.querySelector('#scanButton')
    const select = document.querySelector('#inputCode')

    // Check if device has camera
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
        // Set background color to red
        scanButton.disabled = true;
        console.log('No camera found!')
    }

    // Check if BarcodeDetector is supported
    if (!('BarcodeDetector' in window)) {
        scanButton.disabled = true;
        console.log('BarcodeDetector is not supported by this browser!')
    }


    video.addEventListener("click", () => {
        videoDialog.close()
    });

    videoDialog.addEventListener("close", () => {
        // Stop video stream & scan
        if (video.srcObject) {
            video.srcObject.getTracks().forEach(track => track.stop())
        }

        if (videoDialog.returnValue) {
            select.value = videoDialog.returnValue
            console.log(select.value)
            select.dispatchEvent(new Event('change'))
        }
    })

    // Open the dialog
    scanButton.addEventListener('click', () => {

        if (!videoDialog.open) videoDialog.showModal()
        // Use video without audio
        const constraints = {
            audio: false,
            video: {
                facingMode: 'environment'
            },
        }

        // Start video stream
        console.log('Start video stream')
        navigator.mediaDevices.getUserMedia(constraints)
            .then(stream => video.srcObject = stream)
            .then(() => setInterval(detectCode, 100))
            .catch(err => console.error(err));

        // Create new barcode detector
        // NB: liste des formats possibles : https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detector
        const barcodeDetector = new BarcodeDetector({ formats: ['qr_code'] });

        // Detect code function
        const detectCode = () => {
            // Start detecting codes on to the video element
            barcodeDetector.detect(video).then(codes => {
                // If no codes exit function
                if (codes.length === 0) return;

                for (const barcode of codes) {
                    // Log the barcode to the console
                    console.log(barcode);

                    // Get the barcode value
                    //select.value = barcode.rawValue
                    //select.setValue([barcode.rawValue])

                    // http[s]://[...]?t=[token]
                    videoDialog.returnValue = barcode.rawValue.replace(/^.*\?t=/, '');

                    videoDialog.close();
                    return;
                }
            }).catch(err => {
                // Log an error if one happens
                console.error(err);
            })
        }

    })
</script>

{% endblock content %}

templates/game/end.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper">
        
    <div class="clouds"></div>

    <div class="content">

        <section>

            <div class="logo"><img src="/img/title.png" alt="Grand Prix de la chanson"></div>

            {% if app_gpdc %}
                <p>Et voilà ! Vous avez noté tous nos candidats !</p>
                <p>Grâce à vos votes, l'un d'entre eux remportera le Prix du Public !</p>
                <p>Merci de votre participation !</p>
            {% else %}
                <p>Bravo, vous avez terminé le grand jeu <strong>Vikings</strong> !</p>
                <p>Peut-être remporterez vous l’un des nombreux lots dès maintenant ou par tirage au sort le 3 avril.</p>
            {% endif %}

            {% if app_fbshare %}
                <p>En attendant, <strong>doublez vos chances</strong> en partageant le jeu sur Facebook</p>
                <p><a href="{{ path('game_share') }}" target="_blank" class="button redButton">Partager</a></p>
            {% endif %}

        </section>

        

        {% if app_gpdc %}
            <section class="graySection">
                <p><img src="/img/lillebonne.png" alt="Ville de Lillebonne"></p>
            </section>
        {% else %}
            <section class="graySection">
                <h2>Des dizaines de cadeaux à gagner !</h2>
                <h3>Gagnez à tout moment !</h3>
                <p>Vous pouvez gagner à tout moment : écoutez bien la sono de la foire, un gagnant est désigné toute les 30 minutes en moyenne !</p>
                <h3>Grand tirage au sort !</h3>
                <p>Et à la fin de la foire, un grand tirage au sort désignera les heureux gagnants des "gros lots" !</p>
                <p>Pour en savoir plus,<br>consultez le <a href="{{ asset('reglement2022.pdf') }}" target="_blank">règlement</a></p>
            </section>
        {% endif %}

    </div>

</div>
{% endblock content %}

templates/game/halls.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper">

    <div class="clouds"></div>

    <div class="content">

        {% if app_gpdc %}

            <section>

                <h1>Sélectionnez un candidat</h1>

                <p>Vous pouvez voter une fois par candidat.</p>

                <ul class="hallSelector">
                    {% for hall in halls %}
                        <li>
                            {% if player.isHallDone(hall.id) %}
                                <a href="{{ path('game_hall', {name: hall.name}) }}" class="done">{{ hall.tri }} - {{ hall.name }}</a>
                            {% else %}
                                <a href="{{ path('game_hall', {name: hall.name}) }}">{{ hall.tri }} - {{ hall.name }}</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>

            </section>

        {% else  %}

            <section>

                <h1>Dans quel hall partez-vous en raid ?</h1>

                <p>Sélectionnez le hall dans lequel vous vous trouvez.</p>

                <ul class="hallSelector">
                    {% for hall in halls %}
                    <li>
                        {% if player.isHallDone(hall.id) %}
                            <a href="{{ path('game_hall', {name: hall.name}) }}" class="done">{{ hall.name }}</a>
                        {% else %}
                            <a href="{{ path('game_hall', {name: hall.name}) }}">{{ hall.name }}</a>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>

            </section>

        {% endif %}

        {% if app_fbshare %}
            <section class="graySection">
                <h2>Doubler mes chances</h2>
                <p>Partagez le jeu sur Facebook pour soutenir la Foire de Rouen et doubler vos chance d’être tiré au sort !</p>
                <p><a href="{{ path('game_share') }}" target="_blank" class="button redButton">Partager</a></p>
            </section>
        {% endif %}

    </div>
</div>


{% endblock content %}

templates/game/login.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

    <div id="mainWrapper">

        <div class="clouds"></div>

        <div class="content">

            <section>

                <h1>Connexion</h1>

                <form method="post">

                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

                    <p>
                        <label for="email">Email</label>
                        <input id="email" name="_username" value="{{ last_username }}" type="text" autocomplete="email" required class="block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-teal-500 sm:text-sm sm:leading-6">
                    </p>

                    <p>
                        <label for="password">Mot de passe</label>
                        <input id="password" name="_password" type="password" autocomplete="current-password" required class="block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-teal-500 sm:text-sm sm:leading-6">
                    </p>

                    <p class="mtm"><button class="button redButton blockButton">Valider</button></p>

                    {% if app_inscription %}
                    <a href="{{ path('app_register') }}" class="button redButton">M'inscrire</a>
                    {% endif %}

                    {% if app_login_code %}
                    <a href="{{ path('app_login_code') }}" class="button redButton">j'ai un code</a>
                    {% endif %}


                </form>

            </section>

        </div>
    </div>

{% endblock content %}

templates/game/question.html.twig
{% extends 'game/base.html.twig' %}

{% block content %}

<div id="mainWrapper">
        
    <div class="clouds"></div>

    <div class="content">

        {% if app_gpdc %}

            <section>

                <h5>Candidat n°{{ hall.tri }}</h5>

                <h1 class="nomargin">Notez la prestation de {{ hall.name }} ?</h1>

                <p>&nbsp;</p>

                <p><em>{{ question.text|raw }}</em></p>

                <form method="post">
                    <ul class="buttonList">
                        <li><button name="answer" value="1">&starf; &star; &star; &star; &star;</button></li>
                        <li><button name="answer" value="2">&starf; &starf; &star; &star; &star;</button></li>
                        <li><button name="answer" value="3">&starf; &starf; &starf; &star; &star;</button></li>
                        <li><button name="answer" value="4">&starf; &starf; &starf; &starf; &star;</button></li>
                        <li><button name="answer" value="5">&starf; &starf; &starf; &starf; &starf;</button></li>
                    </ul>
                </form>

                <br>
                <a href="{{ path('game_halls') }}">Retour à la liste des candidats</a>

            </section>

        {% else %}

            <section>

                <h5>{{ hall.name }}</h5>

                <h1 class="nomargin">{{ question.question|raw }}</h1>

                <p>&nbsp;</p>

                <p><em>{{ question.text|raw }}</em></p>

                <form method="post">
                    <ul class="buttonList">
                    {% for answer in question.answersRandom %}
                        <li><input type="submit" name="answer" value="{{ answer }}"></li>
                    {% endfor %}
                    </ul>
                </form>

                <br>
                <a href="{{ path('game_halls') }}">Retour à la liste des halls</a>

            </section>

        {% endif %}

        {% if pubs|length > 0 %}
            <section class="graySection">

                <h2>Nos partenaires du hall {{ hall.name }} :</h2>

                {% for pub in pubs %}
                    <p>
                        {% if pub.link is not null %}<a href="{{ pub.link }}" target="_blank">{% endif %}
                            <img src="/imgpub/{{ pub.image }}" width="300px">
                            {% if pub.link is not null %}</a>{% endif %}
                    </p>
                {% endfor %}

            </section>
        {% endif %}

    </div>
</div>


{% endblock content %}